language: java
dist: trusty
jdk: oraclejdk8

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

install:
  # Download and unzip the Android command line tools (if not already there thanks to the cache mechanism)
  # Latest version of this file available here: https://developer.android.com/studio/#command-tools
  - if test ! -e $HOME/android-sdk-dl/cmdline-tools.zip ; then curl https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip > $HOME/android-sdk-dl/cmdline-tools.zip ; fi
  - unzip -qq -n $HOME/android-sdk-dl/cmdline-tools.zip -d $HOME/android-sdk-dl

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk-dl/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk 'platform-tools' > /dev/null
  # Latest version of build-tools available here: https://developer.android.com/studio/releases/build-tools.html
  - echo y | $HOME/android-sdk-dl/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk 'build-tools;29.0.3' > /dev/null
  - echo y | $HOME/android-sdk-dl/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk 'platforms;android-29' > /dev/null

env:
  - ANDROID_HOME=$HOME/android-sdk

script: ./gradlew --no-daemon --parallel lintDebug testDebug
